apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: back_pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /back_creation
    type: DirectoryOrCreate