apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: back_pvc
spec:
  volumeName: back_pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    request:
      storage: 1Gi