apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-declarative-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: app-declarative-frontend
        tier: frontend
    spec:
      containers:
        - name: frontendc
          image: tiagoconceicao/frontend