apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-declarative
      tier: mongodb
  template:
    metadata:
      labels:
        app: app-declarative
        tier: mongodb
    spec:
      containers:
        - name: mongodb
          image: tiagoconceicao/mongo
          volumeMounts:
            -mountPath: /data/db/
             name: mongo_volume
      volumes:
        - name: mongo_volume
          persistentVolumeClaim:
            claimName: mongo-pvc