apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo_pvc
spec:
  volumeName: mongo_pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    request:
      storage: 1Gi